/**
 * Guards for the www surface that its own scripts cannot express.
 *
 * `scripts/check-design-system.mjs` walks `sites/www` and enforces the palette,
 * the radius, the ban list and the single typeface. Two of its findings there
 * are legitimately exempt — the `theme-color` literal and the `@font-face` that
 * declares the family — and an exemption is a hole unless something narrower
 * closes it. That is what this file is for.
 *
 * `.220`'s rule applies: these assert a parsed shape, and each one was mutated
 * to confirm it goes red before being kept.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import path from 'node:path';

const root = path.join(import.meta.dirname, '..', '..');
const read = (p: string) => readFileSync(path.join(root, p), 'utf8');

const GLOBAL_CSS = 'sites/www/src/styles/global.css';
const TOKENS_CSS = 'sites/www/src/styles/tokens.css';

test('the www surface declares exactly one typeface, and it is Archivo', () => {
  /*
   * global.css is allowlisted for `second-typeface` because @font-face has to
   * name the family literally. That exemption is per-file, so a SECOND
   * @font-face for a different family would inherit it silently — which is the
   * whole reason a blanket exemption is dangerous.
   */
  const css = read(GLOBAL_CSS);
  const families = [...css.matchAll(/@font-face\s*\{[^}]*?font-family:\s*(['"]?)([^;'"]+)\1/gs)].map(
    (m) => m[2].trim()
  );

  assert.equal(
    families.length,
    1,
    `sites/www declares ${families.length} @font-face families (${families.join(', ')}) — the design system is one face, and the allowlist row for this file exempts the rule that would otherwise say so`
  );
  assert.match(
    families[0],
    /archivo/i,
    `the declared family is "${families[0]}" — Archivo is the only face on this system`
  );
});

test('the generated token file is generated, and says so', () => {
  /*
   * tokens.css is written by scripts/build-marketing-tokens.mjs and committed.
   * A hand-edit is drift that check-token-sync catches on VALUES — but only for
   * the seven colours it compares. The banner is what tells the next reader not
   * to edit the other six by hand in the first place.
   */
  assert.ok(existsSync(path.join(root, TOKENS_CSS)), `${TOKENS_CSS} is missing — run npm run www:tokens`);
  const css = read(TOKENS_CSS);
  assert.match(css, /GENERATED by scripts\/build-marketing-tokens\.mjs/, `${TOKENS_CSS} lost its generated-file banner`);
  assert.match(css, /do not edit/i, `${TOKENS_CSS} must tell a reader not to hand-edit it`);
});

test('no colour is typed into the www surface outside the generated tokens', () => {
  /*
   * The narrow half of what the allowlist row for Base.astro gives away. That
   * row exempts the whole `off-palette-colour` rule for the layout, so a stray
   * hex anywhere else in that file would ride along; here the layout is allowed
   * exactly one literal, in a `theme-color` meta tag, and nowhere else.
   */
  /*
   * Comments blanked first, for the same reason check-design-system blanks
   * them: the comment above the meta tag explains *why* the literal is
   * unavoidable, and naming the value is how it explains it. A guard that
   * punishes the explanation gets the explanation deleted, not the hex.
   * (This test's own first run failed on its own comment.)
   */
  const layout = read('sites/www/src/layouts/Base.astro').replace(/<!--[\s\S]*?-->/g, (m) =>
    m.replace(/[^\n]/g, ' ')
  );
  const hexes = [...layout.matchAll(/#[0-9a-fA-F]{3}(?:[0-9a-fA-F]{3})?\b/g)].map((m) => m[0]);
  const inThemeColor = [
    ...layout.matchAll(/name="theme-color"\s+content="(#[0-9a-fA-F]{3,6})"/g),
  ].map((m) => m[1]);

  assert.equal(
    hexes.length,
    inThemeColor.length,
    `Base.astro carries ${hexes.length} hex literal(s) but only ${inThemeColor.length} in theme-color (${hexes.join(', ')}) — the allowlist row covers the meta tag, not the file`
  );
  assert.equal(inThemeColor.length, 1, 'expected exactly one theme-color meta tag');
});

test('poster-close carries display type only; small text goes on poster-field', () => {
  /*
   * The measured rule, from DESIGN_SYSTEM.md and from the contrast table in
   * brand-guidelines.md: paper on `--accent-poster` #ec3013 is 4.19:1, which
   * clears the 3:1 large text needs and fails the 4.5:1 small text needs.
   * Nothing on #ec3013 reaches 4.5:1, not even pure white. `--primary` #ae1800
   * is 6.5:1 and is what a field carrying a kicker or a sub-line must use.
   *
   * This shipped wrong on the first build of the page: a `.poster-close` footer
   * with a 13px `.eyebrow` in it, whose `muted-foreground` is an ink value, so
   * it rendered as dark grey on red. The prose rule existed and did not stop it;
   * a rendered screenshot did. This is that screenshot, as a check.
   */
  const dir = path.join(root, 'sites/www/src');
  if (!existsSync(dir)) return;

  const files: string[] = [];
  const walk = (d: string) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, e.name);
      if (e.isDirectory()) walk(full);
      else if (/\.astro$/.test(e.name)) files.push(full);
    }
  };
  walk(dir);
  assert.ok(files.length > 0, 'no .astro files found — this check would pass over nothing');

  for (const file of files) {
    const src = readFileSync(file, 'utf8').replace(/<!--[\s\S]*?-->/g, '');
    if (!/\bposter-close\b/.test(src)) continue;
    // Everything from the poster-close element to the end of its block. Crude,
    // deliberately: any small-text class anywhere in a file that uses
    // poster-close is worth a human look, and there is exactly one such block
    // per page by design.
    const smallText = src.match(/\b(eyebrow|text-\[1[0-5]px\]|text-xs|text-sm)\b/);
    assert.equal(
      smallText,
      null,
      `${path.relative(root, file)} uses .poster-close alongside "${smallText?.[0]}" — small text on #ec3013 cannot reach 4.5:1. Use .poster-field (#ae1800, 6.5:1).`
    );
  }
});

function wwwAstroFiles(): string[] {
  const dir = path.join(root, 'sites/www/src');
  if (!existsSync(dir)) return [];
  const files: string[] = [];
  const walk = (d: string) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, e.name);
      if (e.isDirectory()) walk(full);
      else if (/\.astro$/.test(e.name)) files.push(full);
    }
  };
  walk(dir);
  return files;
}

test('the www surface never imports app code at runtime', () => {
  /*
   * Build-time frontmatter may read src/lib/contentFloors.ts — that is the point,
   * it is how the exercise count stays honest. What must not happen is an island
   * importing from src/: src/i18n/landingLocales.ts alone is one 52KB module
   * whose fifteen packs cannot be tree-shaken (dynamic BY_LANG indexing plus
   * `...LANDING_EN` spread inheritance), so a single client-side import ships
   * every locale to a visitor who reads one.
   *
   * Discovered, not listed: a two-file enumeration went stale the day `/week`
   * landed. Walking every `.astro` file is the same shape as the poster-close
   * check above it.
   */
  const files = wwwAstroFiles();
  assert.ok(files.length > 0, 'no .astro files found — this check would pass over nothing');
  for (const file of files) {
    const src = readFileSync(file, 'utf8');
    const clientDirective = /client:(load|idle|visible|only|media)/.test(src);
    const importsLocales = /from ['"][^'"]*i18n\/[^'"]*Locales['"]/.test(src);
    assert.ok(
      !(clientDirective && importsLocales),
      `${path.relative(root, file)} hydrates a component AND imports a locale pack — that ships all 15 packs to the browser`
    );
  }
});

test('/week is a terminal landing with a real link home', () => {
  /*
   * The unbuilt request from the `.644` session: combine the three concepts
   * into one continuous-scroll page, with INVITE_URL as the action and a link
   * to the homepage. A landing whose CTA is still `/#invite` or whose home
   * link is missing is the `.640` defect on a new route.
   */
  const page = read('sites/www/src/pages/week.astro');
  assert.match(page, /\bterminal\b/, '/week must terminate at the private gate, not hand off to /start');
  assert.match(page, /href="\/"/, '/week must link to the homepage');
  assert.match(
    read('sites/www/src/components/CtaSlot.astro'),
    /INVITE_URL/,
    'CtaSlot is the one home for the invite URL — /week must not type a second one'
  );
  assert.equal(
    (page.match(/<CtaSlot\b[^>]*\bterminal/g) ?? []).length >= 1,
    true,
    '/week must pass terminal to CtaSlot so the action is INVITE_URL'
  );
});

test('/week copy does not invent traction or a before-after', () => {
  /*
   * Same ban as the homepage (`.640`). The combined landing is three verbs,
   * not a pitch. A mutant that adds "we're live" or "gym-bro" must go red.
   */
  const copy = [
    read('sites/www/src/lib/weekContent.ts'),
    read('sites/www/src/pages/week.astro'),
    read('sites/www/src/components/WeekBreak.astro'),
    read('sites/www/src/components/AnywherePin.astro'),
    read('sites/www/src/components/FieldManual.astro'),
  ].join('\n');
  assert.doesNotMatch(copy, /\b\d[\d,.]*\s*(athletes|users|sign-?ups)\b/i);
  assert.doesNotMatch(copy, /we're live/i);
  assert.doesNotMatch(copy, /before[\s-]*after/i);
  assert.doesNotMatch(copy, /gym-bro/i);
});

test('/about is additive Astro and does not steal the Next host', () => {
  /*
   * G3. Commissioned fourth-surface about page. Next keeps
   * www.missionwinning.com, the ~250 SEO URLs, and Next /about.
   */
  const page = read('sites/www/src/pages/about.astro');
  const copy = [page, read('sites/www/src/lib/aboutContent.ts')].join('\n');
  assert.match(page, /\bterminal\b/, '/about must terminate at the private gate');
  assert.match(page, /href="\/"/, '/about must link to the homepage');
  assert.ok(
    existsSync(path.join(root, 'src/page-components/AboutPage.tsx')),
    'Next /about stays — this loop does not move the SEO URL'
  );
  assert.equal(
    existsSync(path.join(root, 'sites/www/public/_redirects')),
    false,
    'no _redirects — do not steal www.missionwinning.com'
  );
  assert.equal(
    existsSync(path.join(root, 'sites/www/wrangler.toml')),
    false,
    'no wrangler.toml — host split stays undecided'
  );
  assert.doesNotMatch(copy, /america|Presidential Fitness/i);
  assert.doesNotMatch(copy, /\b\d[\d,.]*\s*(athletes|users|sign-?ups)\b/i);
  assert.doesNotMatch(copy, /we're live/i);
  assert.match(copy, /Mission Winning LLC/);
  assert.match(copy, /Texas/);
});

test('/vision is additive Astro and does not steal the Next host', () => {
  /*
   * C1. Commissioned fourth-surface vision page. Next keeps
   * www.missionwinning.com and Next /vision.
   */
  const page = read('sites/www/src/pages/vision.astro');
  const copy = [page, read('sites/www/src/lib/visionContent.ts')].join('\n');
  assert.match(page, /\bterminal\b/, '/vision must terminate at the private gate');
  assert.match(page, /href="\/"/, '/vision must link to the homepage');
  assert.ok(
    existsSync(path.join(root, 'src/page-components/VisionPage.tsx')),
    'Next /vision stays — this loop does not move the SEO URL'
  );
  assert.equal(
    existsSync(path.join(root, 'sites/www/public/_redirects')),
    false,
    'no _redirects — do not steal www.missionwinning.com'
  );
  assert.doesNotMatch(copy, /america|Presidential Fitness/i);
  assert.doesNotMatch(copy, /\b\d[\d,.]*\s*(athletes|users|sign-?ups)\b/i);
  assert.match(copy, /free forever/i);
  assert.match(copy, /no wearable required/i);
});

test('/compare is an index; Next keeps the vs stories', () => {
  const page = read('sites/www/src/pages/compare.astro');
  const copy = [page, read('sites/www/src/lib/compareContent.ts')].join('\n');
  assert.match(page, /\bterminal\b/);
  assert.match(copy, /mission-winning-vs-hevy/);
  assert.match(copy, /mission-winning-vs-strong/);
  assert.match(copy, /mission-winning-vs-fitbod/);
  assert.ok(existsSync(path.join(root, 'src/page-components/LearnVsPublicPage.tsx')));
  assert.equal(existsSync(path.join(root, 'sites/www/public/_redirects')), false);
  assert.doesNotMatch(copy, /america|Presidential Fitness/i);
  const stories = copy.match(/mission-winning-vs-/g) ?? [];
  assert.ok(stories.length >= 3);
});

test('/week anywhere movement keeps three photographs and two plates', () => {
  /*
   * Concept 02's honest greybox: five places, three frames in the repo.
   * Dropping a photograph to "simplify" the pin is how the page becomes a
   * wireframe again — the composition floor would still pass on the hero
   * alone. Count the optional `photo:` fields inside CHAPTERS.
   */
  const src = read('sites/www/src/lib/weekContent.ts');
  const block = src.slice(src.indexOf('export const CHAPTERS'), src.indexOf('export type SpecRow'));
  const photos = block.match(/photo:/g) ?? [];
  assert.equal(photos.length, 3, `CHAPTERS has ${photos.length} photographs; the greybox is three frames, five places`);
  assert.match(src, /export const PIN/, '/week HUD copy must live next to the week it displays');
});
